version: '3'
services:
  web:
    build:
      context: .
    container_name: task_manager_django
    restart: unless-stopped
    volumes:
      - .:/code
      - ./task_manager/deployment/gunicorn/logs:/task_manager/deployment/gunicorn/logs
      - static:/code/static
      - media:/code/media
    # networks:
    #   - internal
    depends_on:
      - postgres

  postgres:
    build: ./task_manager/deployment/postgres
    container_name: task_manager_db
    restart: unless-stopped
    expose:
      - "5432"
    environment:
      - LC_ALL=${LC_ALL}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    # networks:
    #   - internal
    volumes:
      - pgdata:/var/lib/postgresql/data/

  pgadmin:
    image: dpage/pgadmin4
    container_name: task_manager_pg_admin
    # networks:
    #   - internal
    depends_on:
      - postgres
    ports:
      - "5055:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    restart: always

  nginx:
    restart: always
    build: ./task_manager/deployment/nginx
    container_name: task_manager_web_server
    volumes:
      - ./task_manager/deployment/nginx/:/etc/nginx/conf.d
      - ./task_manager/deployment/nginx/logs/:/code/logs/nginx
      - static:/code/static
      - media:/code/media
    ports:
      - "127.0.0.1:8000:80"
    depends_on:
      - web
    links:
      - web

# networks:
#   internal:


volumes:
  pgdata:
  media:
  static:
