# Generated by Django 4.2.2 on 2023-06-20 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="name",
            new_name="title",
        ),
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("TODO", "Todo"),
                    ("IN_PROGRESS", "In progress"),
                    ("BLOCKED", "Blocked"),
                    ("IN_REVIEW", "in Review"),
                    ("READY_FOR_QA", "Ready for QA"),
                    ("IN_QA", "In QA"),
                    ("READY_FOR_DEPLOYMENT", "Ready for Deployment"),
                    ("DONE", "Done"),
                ],
                default="TODO",
                max_length=40,
            ),
        ),
    ]
