# Generated by Django 4.2.2 on 2023-06-19 21:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("login", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="useraccount",
            name="role",
            field=models.TextField(
                choices=[
                    ("EXCE", "EXCE"),
                    ("ADMIN", "ADMIN"),
                    ("STAFF", "STAFF"),
                    ("SUPPORT_STAFF", "SUPPORT_STAFF"),
                ],
                default="SUPPORT_STAFF",
                max_length=30,
            ),
        ),
    ]
