# Generated by Django 4.2.2 on 2023-06-19 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0002_useraccount_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useraccount",
            name="role",
            field=models.TextField(
                choices=[
                    ("EXEC", "Exec"),
                    ("ADMIN", "Admin"),
                    ("STAFF", "Staff"),
                    ("SUPPORT_STAFF", "Support Staff"),
                ],
                default="SUPPORT_STAFF",
                max_length=30,
            ),
        ),
    ]
