# Generated by Django 4.2.2 on 2023-06-20 06:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("login", "0003_alter_useraccount_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useraccount",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[
                    ("MALE", "Male"),
                    ("FEMALE", "Female"),
                    ("OTHER", "Other"),
                ],
                max_length=10,
                null=True,
            ),
        ),
    ]
